#!/usr/bin/env bash
# fizzbuzz

i=0

while [ $i -lt 100 ]
do
  ((i++))
  if ! ((i % 15))
	then
	echo "FizzBuzz"
  elif ! ((i % 3))
	then
	echo "Fizz"
  elif ! ((i % 5))
	then
	echo "Buzz"

	else
  	  echo $i
fi

done

