#!/usr/bin/env bash
# script that displays Best School 10 times.


i=0

while [ $i -lt 8 ]
do
  ((i++))
  if [[ "$i" == '4' ]]
	then
	echo "bad luck"
	elif [[ "$i" == '7' ]]
	then
	echo "good luck"

fi
  echo "Best School"
done

