#!/usr/bin/env bash
# script that displays Best School 10 times.


h=0
m=1

echo "Hour: "$h
while [ $h -lt 13 ]
	do
	while [ $m -lt 59 ]

		echo $m
		((m++))
		do

	  	if [[ "$m" == '60' ]]
			then
			((h++))
			if [[ "$h" == '13' ]]
				then
				break

			else
			    echo "Hour: "$h
			m=1
		fi
		fi

	done
done
